# Workflow configuration file for GitHub actions for Azure postgresql server
name: postgresql_pg-test-repo_azure_sys

on: 
  push: 
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/postgresql@v1
      with:
        server-name: azure_sys
        connection-string: ${{ secrets.AZURE_POSTGRESQLFLEXIBLE_CONNECTION_STRING }}
        plsql-file: ""

    - name: logout
      run: |
        az logout